### ISSUE TITLE
Buffer is not defined 

### ISSUE THREAD

**Issue by Manitej66** [faceteer/expression-builder#1]
I'm trying to generate the filter expression for the example in docs, but it's throwing me error
```
Uncaught ReferenceError: Buffer is not defined
    at isBinary (@faceteer_expression-builder.js:8299:7)
    at typeOf (@faceteer_expression-builder.js:8271:37)
    at Function.input (@faceteer_expression-builder.js:8376:41)
    at getValue (@faceteer_expression-builder.js:8705:43)
    at condition (@faceteer_expression-builder.js:8630:57)
    at Object.filter (@faceteer_expression-builder.js:8712:14)
    at scanTable (:3000/src/data/aws/dynamodb.ts?t=1645279517406:45:42)
    at Explorer (:3000/src/App/Stage/DynamoDB/index.tsx?t=1645279517406:257:16)
    at renderWithHooks (:3000/node_modules/.vite/chunk-5O6CSMVN.js?v=c3021917:11061:26)
    at mountIndeterminateComponent (:3000/node_modules/.vite/chunk-5O6CSMVN.js?v=c3021917:13181:21)
```

**Comment by Manitej66** [comment]
if anyone facing above issue in vite, follow the below steps:

1. `yarn add buffer`
2.  Go to `main.jsx` and add below 2 lines
```js
import { Buffer } from "buffer";
window.Buffer = Buffer;
```
